### ISSUE TITLE
Use SCSS

### ISSUE THREAD

**Issue by zmontgo** [benjaminbhollon/see-with-eyes-closed#6]
Use SCSS to make it easier for the contributors and the server. If you want to debate this in the discussion thread of this issue, feel free ;)

**Comment by benjaminbhollon** [comment]
My problem with SCSS is that it's just cosmetic. Nothing at all changes for the users, and it adds an extra step (compiling) to the workflow. It also means that people who do want to help out might have to learn a new language. SCSS devs can code in CSS, but it's hard for CSS devs to code in SCSS.

**Comment by zmontgo** [comment]
By that logic, writing clean code is also 'cosmetic'. Sure, it isn't technically necessary to take the time to write code with good style, but it helps make it clear what you're doing. Even is SCSS was just cosmetic (it's not, it includes some great things like being able to compile directly into a compressed format while being able to work with multiple files to separate things out), it helps immensely while writing and reading code. SCSS has also been written to be clear to CSS developers, it's really not that difficult of a language to learn. I could argue that using Pug is just cosmetic, but you chose it because it's clear and it cuts down on the amount of line length and file space. The way your code looks is just as important as how the final product looks.

**Comment by benjaminbhollon** [comment]
But CSS is perfectly fine as to writing clean code. Writing clean code
is so that other developers are able to read it. As I said, CSS devs
can't read SCSS, but SCSS devs can read CSS. I'd rather go for greater
support.

I didn't choose pug because it cuts down on line length and file
space, I chose it because it was a templating engine that could take
direct input from ExpressJS and change the HTML accordingly. I would
never have chosen it if all it did was cut down file size.

On 1/23/21, Zachary M. <notifications@github.com> wrote:
> By that logic, writing clean code is also 'cosmetic'. Sure, it isn't
> technically necessary to take the time to write code with good style, but it
> helps make it clear what you're doing. Even is SCSS was just cosmetic (it's
> not, it includes some great things like being able to compile directly into
> a compressed format while being able to work with multiple files to separate
> things out), it helps immensely while writing and reading code. SCSS has
> also been written to be clear to CSS developers, it's really not that
> difficult of a language to learn. I could argue that using Pug is just
> cosmetic, but you chose it because it's clear and it cuts down on the amount
> of line length and file space. The way your code looks is just as important
> as how the final product looks.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/benjaminbhollon/see-with-eyes-closed/issues/6#issuecomment-765838387


-- 

Your friend,
  Benjamin Hollon

I'm Currently Reading:
<https://www.goodreads.com/user/email_signature_destination/80839667?utm_medium=reading_link&utm_source=email_signature>
[image: Book Cover]
<https://www.goodreads.com/user/email_signature_destination/80839667?utm_medium=cover&utm_source=email_signature>
